In [1]:
#Perceptrons

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd

In [74]:
class Perceptron:
  def __init__(self,lr,iter):
    self.weights = np.random.randn(3) * 1e-4
    print(f"Weights: {self.weights}")
    self.lr = lr
    self.iter = iter

  def activation_function(self,input,weights):
    z=np.dot(input,weights)
    return np.where(z<0,0,1)

  def fit(self,X,y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
    print(f"X with Bias:\n {X_with_bias}")

    for n in range(self.iter):
      y_hat = self.activation_function(X_with_bias,self.weights)
      print(f"Actual Value:\n {self.y}")
      print(f"Predicted Value:\n {y_hat}")

      error = self.y - y_hat
      print(f" Error:\n {error}")

      self.weights = self.weights + self.lr * np.dot(X_with_bias.T,error)
      print(f"Updated weights:\n {self.weights}")
      print("#############\n")

  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
    return self.activationFunction(X_with_bias, self.weights)



In [68]:
model = Perceptron(0.5,10)

Weights: [ 4.62819646e-05 -5.66126516e-05 -8.54345329e-05]


In [69]:
#AND function
data = {"x1" : [0,0,1,1], "x2": [0,1,0,1],"y":[0,0,0,1]}
df = pd.DataFrame(data)

In [70]:
df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [71]:
X=df.drop(columns=['y'])
y=df['y']

In [72]:
y.to_frame()

y
0  0
1  0
2  0
3  1

In [73]:
model.fit(X,y)

X with Bias:
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Actual Value:
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Predicted Value:
 [1 1 1 1]
 Error: 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights:
 [-0.49995372 -0.50005661  1.49991457]
#############

Actual Value:
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Predicted Value:
 [0 0 0 0]
 Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights:
 [ 4.62819646e-05 -5.66126516e-05  9.99914565e-01]
#############

Actual Value:
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Predicted Value:
 [0 0 0 0]
 Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights:
 [0.50004628 0.49994339 0.49991457]
#############

Actual Value:
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Predicted Value:
 [0 1 1 1]
 Error: 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights:
 [ 4.62819646e-05 -5.66126516e-05  1.49991457e+00]
#############

Actual Value:
 0

In [63]:
#OR function
data = {"x1" : [0,0,1,1], "x2": [0,1,0,1],"y":[0,1,1,1]}
df = pd.DataFrame(data)

In [64]:
X=df.drop(columns=['y'])
y=df['y']

In [65]:
model = Perceptron(0.5,10)

Weights: [-1.08726684e-04 -1.05950359e-04 -2.38738460e-05]


In [66]:
model.fit(X,y)

X with Bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Actual Value: 0    0
1    1
2    1
3    1
Name: y, dtype: int64
Predicted Value: [1 0 0 0]
 Error: 0   -1
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights: [ 0.99989127  0.99989405 -1.00002387]
#############

Actual Value: 0    0
1    1
2    1
3    1
Name: y, dtype: int64
Predicted Value: [1 1 1 1]
 Error: 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: [ 0.99989127  0.99989405 -0.50002387]
#############

Actual Value: 0    0
1    1
2    1
3    1
Name: y, dtype: int64
Predicted Value: [1 1 1 1]
 Error: 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: [ 9.99891273e-01  9.99894050e-01 -2.38738460e-05]
#############

Actual Value: 0    0
1    1
2    1
3    1
Name: y, dtype: int64
Predicted Value: [1 1 1 1]
 Error: 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: [0.99989127 0.99989405 0.49997613]
#############

Actual Value: 0    0
1    1
2    1
3    1